In [3]:
import numpy as np
print("NumPy version:", np.__version__)
print("Ready to go! 🚀")

NumPy version: 2.0.2
Ready to go! 🚀


MULTIDIMENTIONAL ARRAYS

In [4]:
p=np.array([1,23,44,5,566,778,89])
print(p*2)

[   2   46   88   10 1132 1556  178]


In [20]:
p=np.array([[[1.0,2.0,6.0,0.0,0.0], [12.0,3.0,4.0,5.0,66.0], [3.0,56.0,66.0,77.0,7888.0]]])
print(p)
print(p.ndim)

[[[1.000e+00 2.000e+00 6.000e+00 0.000e+00 0.000e+00]
  [1.200e+01 3.000e+00 4.000e+00 5.000e+00 6.600e+01]
  [3.000e+00 5.600e+01 6.600e+01 7.700e+01 7.888e+03]]]
3


In [35]:
alphabet=np.array([[["a","b","c"],["d","e","f"],["g","h","i"]],
                    [["j","k","l"],["m","n","o"],["p","q","r"]],
                    [["s","t","u"],["v","w","x"],["y","z"," "]]])

word=alphabet[0,0,0]+alphabet[1,0,1]+alphabet[2,0,0]+alphabet[0,2,1]+alphabet[0,0,0]+alphabet[2,0,1]
print(word)

akshat


creating arrays

In [36]:
#zeroes and ones
p=np.zeros(5)
a=np.ones(7)
print(p,a)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1.]


In [40]:
# range of numbers
a=np.arange(1,23,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [42]:
#linespaces
d=np.linspace(0,5,5)
print(d)

[0.   1.25 2.5  3.75 5.  ]


In [67]:
# Random — used in ML weight initialization!
rand=np.random.rand(5)
print(rand)

[0.74706279 0.09247544 0.12006725 0.40099556 0.4291571 ]


In [119]:
#RANDOM SAMPLE:-
P=np.random.random_sample(alphabet.shape)
print(P)

[[[0.61195917 0.20497112 0.84327431]
  [0.93386055 0.03565289 0.3132497 ]
  [0.91532905 0.66428258 0.57641532]]

 [[0.86018038 0.77134074 0.6588531 ]
  [0.1030309  0.42884414 0.33981708]
  [0.51450988 0.48942544 0.06769689]]

 [[0.28042759 0.24487284 0.74444687]
  [0.42793841 0.58832573 0.86456797]
  [0.18839227 0.01730694 0.5399445 ]]]


Index and slicing


In [70]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[-1])
print(a[3])
print(a[a>30])
print(a[a%3==0])
print(a[3:])
print(a[2:])

10
50
40
[40 50]
[30]
[40 50]
[30 40 50]


2D array — think of it as a TABLE

In [156]:
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix.shape)
print(matrix[0])
print(matrix[: ,0])
print(matrix[1][2])
print(matrix[1,2])

#ML CONNECTION

dataset = np.array([
    [25, 50000, 1],
    [30, 75000, 0],
    [35, 90000, 1]
])

ages = dataset[:, 0]
salaries = dataset[:, 1]
labels = dataset[:, 2]

print("ages=",ages,
      "salaries=",salaries,
      "labels=",labels)

(3, 3)
[1 2 3]
[1 4 7]
6
6
ages= [25 30 35] salaries= [50000 75000 90000] labels= [1 0 1]


 Broadcasting

In [157]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

a= matrix+10
print(a)
print("="*40)
new=np.array([1,2,3])
print(matrix+new)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [158]:
# Ml connection
data = np.array([[100, 2], [200, 4], [300, 6]])
mean=data.mean(axis=0)
std=data.std(axis=0)
normalised=(data-mean)/std
print(normalised)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


COPYING OF ARRAYS

In [159]:
#don't
h=np.array([1,2,3])
b=h
b[1]=100
print(h)

#do
h=np.array([1,2,3])
b=h.copy()
b[1]=100
print(h)


[  1 100   3]
[1 2 3]


imp functions

In [160]:
a = np.array([4, 2, 8, 1, 6, 3])  # diference max:maximum value ,argmax=maximum indexing value
print(np.mean(a))
print(np.median(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.argmax(a))
print(np.std(a))
print(np.sort(a))

4.0
3.5
8
1
24
2
2.3804761428476167
[1 2 3 4 6 8]


MINI PROJECT

In [162]:
#building a matrix
output=np.ones((5,5))
print(output)
output1=np.zeros((3,3))
output1[1,1]=9
print(output1)
output[1:4,1:4]=output1
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
p=np.full([5,5] ,2)
print(p)
k=np.full([3,3],5)
k[1,1]=10
p[1:4,1:4]=k
print(p)