In [89]:
import numpy as np
print("NumPy version:", np.__version__)
print("Ready to go! 🚀")

NumPy version: 2.0.2
Ready to go! 🚀


MULTIDIMENTIONAL ARRAYS

In [12]:
p=np.array([1,23,44,5,566,778,89])
print(p*2)

[   2   46   88   10 1132 1556  178]


In [13]:
p=np.array([[[1.0,2.0,6.0,0.0,0.0], [12.0,3.0,4.0,5.0,66.0], [3.0,56.0,66.0,77.0,7888.0]]])
print(p)
print(p.ndim)

[[[1.000e+00 2.000e+00 6.000e+00 0.000e+00 0.000e+00]
  [1.200e+01 3.000e+00 4.000e+00 5.000e+00 6.600e+01]
  [3.000e+00 5.600e+01 6.600e+01 7.700e+01 7.888e+03]]]
3


In [14]:
alphabet=np.array([[["a","b","c"],["d","e","f"],["g","h","i"]],
                    [["j","k","l"],["m","n","o"],["p","q","r"]],
                    [["s","t","u"],["v","w","x"],["y","z"," "]]])

word=alphabet[0,0,0]+alphabet[1,0,1]+alphabet[2,0,0]+alphabet[0,2,1]+alphabet[0,0,0]+alphabet[2,0,1]
print(word)

akshat


creating arrays

In [15]:
#zeroes and ones
p=np.zeros(5)
a=np.ones(7)
print(p,a)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1.]


In [16]:
# range of numbers
a=np.arange(1,23,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [17]:
#linespaces
d=np.linspace(0,5,5)
print(d)

[0.   1.25 2.5  3.75 5.  ]


In [18]:
# Random — used in ML weight initialization!
rand=np.random.rand(5)
print(rand)

[0.46677331 0.04777634 0.16551398 0.52745149 0.95254378]


In [19]:
#RANDOM SAMPLE:-
P=np.random.random_sample(alphabet.shape)
print(P)

[[[0.60582511 0.85853506 0.7545937 ]
  [0.64654698 0.44534958 0.48853778]
  [0.54393248 0.57138409 0.04857879]]

 [[0.96049664 0.93588141 0.67302901]
  [0.81203178 0.34929148 0.52578332]
  [0.67548972 0.08622356 0.47650878]]

 [[0.9707175  0.58300175 0.70277646]
  [0.13815501 0.15855997 0.82012578]
  [0.34052638 0.80925381 0.73375096]]]


Index and slicing


In [20]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[-1])
print(a[3])
print(a[a>30])
print(a[a%3==0])
print(a[3:])
print(a[2:])

10
50
40
[40 50]
[30]
[40 50]
[30 40 50]


2D array — think of it as a TABLE

In [21]:
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix.shape)
print(matrix[0])
print(matrix[: ,0])
print(matrix[1][2])
print(matrix[1,2])

#ML CONNECTION

dataset = np.array([
    [25, 50000, 1],
    [30, 75000, 0],
    [35, 90000, 1]
])

ages = dataset[:, 0]
salaries = dataset[:, 1]
labels = dataset[:, 2]

print("ages=",ages,
      "salaries=",salaries,
      "labels=",labels)

(3, 3)
[1 2 3]
[1 4 7]
6
6
ages= [25 30 35] salaries= [50000 75000 90000] labels= [1 0 1]


 Broadcasting

In [22]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

a= matrix+10
print(a)
print("="*40)
new=np.array([1,2,3])
print(matrix+new)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [23]:
# Ml connection
data = np.array([[100, 2], [200, 4], [300, 6]])
mean=data.mean(axis=0)
std=data.std(axis=0)
normalised=(data-mean)/std
print(normalised)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


COPYING OF ARRAYS

In [24]:
#don't
h=np.array([1,2,3])
b=h
b[1]=100
print(h)

#do
h=np.array([1,2,3])
b=h.copy()
b[1]=100
print(h)


[  1 100   3]
[1 2 3]


imp functions

In [25]:
a = np.array([4, 2, 8, 1, 6, 3])  # diference max:maximum value ,argmax=maximum indexing value
print(np.mean(a))
print(np.median(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.argmax(a))
print(np.std(a))
print(np.sort(a))

4.0
3.5
8
1
24
2
2.3804761428476167
[1 2 3 4 6 8]


basic math algorithms

In [28]:
a=np.array([1,2,3,4])
print(a+2)
print(a*2)
print(a-2)
print(a/2)
print(a**2)
b=np.array([5,6,7,8])
print(a+b)# in adding the first element adds with first element an so on
print(np.sin(a))

[3 4 5 6]
[2 4 6 8]
[-1  0  1  2]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 6  8 10 12]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


linear algebra

In [32]:
a=np.full((2,3),2)
b=np.ones((3,2))
print(a)
print(b)
print(np.matmul(a,b))

[[2 2 2]
 [2 2 2]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[6. 6.]
 [6. 6.]]


In [39]:
#to find determinant
t=np.identity(7)
print(np.linalg.det(t))

1.0


Statics

In [58]:
a=np.array([[1,23,454,55,667,788,5,433,5332,23,456],[12,3,45,6567,433,235,42,5625,23,45,43]])
print(np.max(a, axis=1))
print(np.min(a, axis=1))
print(np.sum(a, axis=1))

[5332 6567]
[1 3]
[ 8237 13073]


Reorganising arrays


In [62]:
a=np.array([[[1,2,3,4],[5,6,7,8]]])
print(a.shape)
print(a.reshape((4,2)))

(1, 2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [67]:
# vertically stacking
a=np.array([1,2,3,4])
output1=np.array((2,2,2,2))
print(np.hstack((a,output1)))
a=np.array([1,2,3,4])
output1=np.array((2,2,2,2))
print(np.vstack((a,output1)))

[1 2 3 4 2 2 2 2]
[[1 2 3 4]
 [2 2 2 2]]


Boolean maskin and advansed indexing


In [82]:
a=np.array([1,23,454,55,667,788,5,433,5332,23,456,12,3,45,6567,433,235,42,5625,23,45,43,234,454,545345,45,45,45235,35345,345,3,5445,453,3424,5])
print(a[a>=50])
#We can use list for indexing
print((~(a >50)&(a<5000)))


[   454     55    667    788    433   5332    456   6567    433    235
   5625    234    454 545345  45235  35345    345   5445    453   3424]
[ True  True False False False False  True False False  True False  True
  True  True False False False  True False  True  True  True False False
 False  True  True False False False  True False False False  True]


MINI PROJECT

In [26]:
#building a matrix
output=np.ones((5,5))
print(output)
output1=np.zeros((3,3))
output1[1,1]=9
print(output1)
output[1:4,1:4]=output1
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
p=np.full([5,5] ,2)
print(p)
k=np.full([3,3],5)
k[1,1]=10
p[1:4,1:4]=k
print(p)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[ 2  2  2  2  2]
 [ 2  5  5  5  2]
 [ 2  5 10  5  2]
 [ 2  5  5  5  2]
 [ 2  2  2  2  2]]


In [97]:
import numpy as np
data=np.array([1,23,4,57,56,7,65,54,89,32,67,2,12,7,1,5,])
print(np.max(data))
print(np.min(data))
print(np.mean(data))
print(data[data>=50])
print(data**2)
mean=np.mean(data)
std=data.std(axis=0)
normalised=(data-mean)/std
print(normalised)

89
1
30.125
[57 56 65 54 89 67]
[   1  529   16 3249 3136   49 4225 2916 7921 1024 4489    4  144   49
    1   25]
[-1.01179147 -0.2475198  -0.9075726   0.93362732  0.8988877  -0.80335374
  1.21154429  0.82940846  2.0452952   0.06513679  1.28102353 -0.97705185
 -0.62965563 -0.80335374 -1.01179147 -0.87283298]
